FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
copy ./target/monitor-service-0.0.1-SNAPSHOT.jar monitor-service-0.0.1-SNAPSHOT.jar
RUN chmod 777 monitor-service-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","monitor-service-SNAPSHOT.jar"]
ENTRYPOINT ["java", "-jar", "/app.jar"]



